import type { Arc } from './arc-utils';

// Арки Наруто с рейтингами IMDB и главами манги
// Источники: IMDB, FandomWire, AnimeFillerGuide, Narutopedia

export const ARCS: Arc[] = [
  // ==================== ПЕРВЫЙ СЕЗОН ====================

  {
    id: 'introduction',
    name: 'Начало пути',
    description: 'Знакомство с Наруто Удзумаки и командой 7. Первые шаги в мире ниндзя.',
    season: 1,
    episodeIds: [1, 2],
    rating: 8.1,
    mangaChapters: '1–33',  // Введение (1–8) + Страна Волн (9–33)
    image: '/images/arcs/introduction.jpg',
  },
  {
    id: 'chunin-exams',
    name: 'Экзамен на звание чунина',
    description: 'Грандиозный турнир, раскрывающий множество персонажей и их способностей.',
    season: 1,
    episodeIds: [3, 4, 5, 6],
    rating: 9.2,
    mangaChapters: '34–115',
    image: '/images/arcs/chunin-exams.jpg',
  },
  {
    id: 'konoha-crush',
    name: 'Вторжение в Коноху',
    description: 'Орочимару атакует Деревню Скрытого Листа. Бой Наруто и Гаары.',
    season: 1,
    episodeIds: [7, 8],
    rating: 8.7,
    mangaChapters: '116–138',
    image: '/images/arcs/konoha-crush.jpg',
  },
  {
    id: 'search-for-tsunade',
    name: 'Поиски Цунаде',
    description: 'Поиск легендарного Саннина. Изучение Расэнгана и бой трёх Саннинов.',
    season: 1,
    episodeIds: [9, 10, 11, 12, 13, 14],
    rating: 8.3,
    mangaChapters: '139–171',
  },
  {
    id: 'season1-films-ova-early',
    name: 'Фильмы и ОВА',
    description: 'Фильм «Принцесса страны Снега» и ранние ОВА.',
    season: 1,
    episodeIds: [15, 16, 17, 18],
  },
  {
    id: 'land-of-tea',
    name: 'Страна Чая',
    description: 'Филлерные миссии — истинное лицо Какаши и гонка в Стране Чая.',
    season: 1,
    episodeIds: [19, 20],
    rating: 7.5,
  },
  {
    id: 'sasuke-recovery',
    name: 'Преследование Саске',
    description: 'Одна из лучших арок — погоня за Саске. Легендарный бой в Долине Завершения.',
    season: 1,
    episodeIds: [21],
    rating: 8.8,
    mangaChapters: '172–238',
    image: '/images/arcs/sasuke-recovery.jpg',
  },
  {
    id: 'filler-missions-1',
    name: 'Филлерные миссии: Часть 1',
    description: 'Проникновение к Орочимару, фильмы 2–3, возвращение Мидзуки и другие задания.',
    season: 1,
    episodeIds: [22, 23, 24, 25, 26, 27],
  },
  {
    id: 'filler-missions-2',
    name: 'Филлерные миссии: Часть 2',
    description: 'Страна Птиц, Страна Моря, Селение Звезды и множество одиночных приключений.',
    season: 1,
    episodeIds: [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 'season1-finale',
    name: 'Финал первого сезона',
    description: 'Одиннадцать из Конохи, клан Курама, Менма и завершение сезона.',
    season: 1,
    episodeIds: [46, 47, 48, 49, 50, 51, 52],
    mangaChapters: '238',
  },

  // ==================== ВТОРОЙ СЕЗОН (Ураганные хроники) ====================

  {
    id: 'kazekage-rescue',
    name: 'Спасение Кадзекаге',
    description: 'Акацуки похищают Гаару. Команда Какаши спешит на помощь.',
    season: 2,
    episodeIds: [53, 54],
    rating: 8.1,
    mangaChapters: '245–281',
  },
  {
    id: 'tenchi-bridge',
    name: 'Долгожданная встреча',
    description: 'Мост Тэнти. Появление Ямато и Сая. Столкновение с Орочимару.',
    season: 2,
    episodeIds: [55, 56, 57],
    rating: 8.4,
    mangaChapters: '282–310',
  },
  {
    id: 'twelve-guardian-ninja',
    name: '12 Ниндзя-Защитников',
    description: 'Прошлое Асумы и тренировка Наруто. Филлерная арка с сюжетными вставками.',
    season: 2,
    episodeIds: [58],
    rating: 7.2,
  },
  {
    id: 'akatsuki-suppression',
    name: 'Бессмертные Акацуки',
    description: 'Хидан и Какузу. Месть Шикамару. Одна из самых жестоких арок.',
    season: 2,
    episodeIds: [59],
    rating: 8.6,
    mangaChapters: '311–342',
  },
  {
    id: 'three-tails',
    name: 'Треххвостая Черепаха',
    description: 'Миссия по поимке Трёххвостого. Смесь сюжета и филлеров.',
    season: 2,
    episodeIds: [60],
    rating: 6.8,
  },
  {
    id: 'jiraiya-itachi',
    name: 'Предсказание и месть',
    description: 'Последний бой Джирайи, легенда об учителе. Правда об Итачи.',
    season: 2,
    episodeIds: [61, 62, 63, 64],
    rating: 9.3,
    mangaChapters: '343–412',
    image: '/images/arcs/jiraiya-itachi.jpg',
  },
  {
    id: 'six-tails',
    name: 'История Шестихвостого',
    description: 'Утаката и его ученица. Филлерная арка между основным сюжетом.',
    season: 2,
    episodeIds: [65, 66],
    rating: 7.0,
  },
  {
    id: 'pains-assault',
    name: 'Нападение Пейна',
    description: 'Пейн уничтожает Коноху. Наруто пробуждает Мудреца. Лучшая арка по рейтингу.',
    season: 2,
    episodeIds: [67, 68, 69],
    rating: 9.6,
    mangaChapters: '413–453',
    image: '/images/arcs/pains-assault.jpg',
  },
  {
    id: 'past-arc-fillers',
    name: 'Хроники Конохи',
    description: 'Фильм «Затерянная башня», рассказы об Ируке, одиночные филлеры.',
    season: 2,
    episodeIds: [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
  },
  {
    id: 'five-kage-summit',
    name: 'Совет Пяти Каге',
    description: 'Саске против Данзо. Объявление Четвёртой мировой войны шиноби.',
    season: 2,
    episodeIds: [89, 90, 91],
    rating: 8.5,
    mangaChapters: '454–483',
  },
  {
    id: 'paradise-life-boat',
    name: 'Рай на корабле',
    description: 'Длинная серия одиночных филлеров на пути к острову Черепахи.',
    season: 2,
    episodeIds: [92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111],
  },
  {
    id: 'taming-nine-tails',
    name: 'Приручение Девятихвостого',
    description: 'Наруто учится контролировать силу Курамы на острове Черепахи.',
    season: 2,
    episodeIds: [112, 113],
    rating: 8.3,
    mangaChapters: '489–515',
  },
  {
    id: 'war-begins',
    name: 'Начало войны',
    description: 'Кармические встречи. Семь Мечников Тумана. Война начинается.',
    season: 2,
    episodeIds: [114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127],
    rating: 8.0,
    mangaChapters: '515–559',
  },
  {
    id: 'war-climax',
    name: 'Кульминация войны',
    description: 'Враги из загробного мира. Саске и Итачи сражаются вместе. АНБУ Какаши.',
    season: 2,
    episodeIds: [128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
    rating: 8.4,
    mangaChapters: '560–639',
    image: '/images/arcs/war-climax.jpg',
  },
  {
    id: 'team7-returns',
    name: 'Возвращение команды №7',
    description: 'Обито раскрыт. Мадара возвращается. Хаширама и Мадара — истоки.',
    season: 2,
    episodeIds: [144, 145, 146, 147, 148, 149, 150, 151, 152],
    rating: 8.2,
    mangaChapters: '640–677',
  },
  {
    id: 'kaguya-final',
    name: 'Кагуя и финальные бои',
    description: 'Вечное Цукуёми. Кагуя Оцуцуки. Наруто против Саске — последний бой.',
    season: 2,
    episodeIds: [153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165],
    rating: 8.5,
    mangaChapters: '678–699',
    image: '/images/arcs/kaguya-final.jpg',
  },
  {
    id: 'epilogue',
    name: 'Эпилог и новое поколение',
    description: 'Отрочество, история Саске, Шикамару, свадьба Наруто и Хинаты.',
    season: 2,
    episodeIds: [166, 167, 168, 169, 170, 171, 172],
    rating: 8.0,
    mangaChapters: '699–700',
    image: '/images/arcs/epilogue.jpg',
  },
  {
    id: 'bonus-boruto',
    name: 'Бонусы и фильм Боруто',
    description: 'ОВА-спецвыпуски и фильм «Наруто: Боруто».',
    season: 2,
    episodeIds: [173, 174, 175],
  },
];
